name: Build ZMK Firmware
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install West
        run: pip install west

      - name: Install Zephyr SDK
        run: |
          wget -q https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.8/zephyr-sdk-0.16.8_linux-x86_64.tar.xz
          tar -xJf zephyr-sdk-0.16.8_linux-x86_64.tar.xz -C /opt
          /opt/zephyr-sdk-0.16.8/setup.sh -t arm-zephyr-eabi
          echo "Zephyr SDK installed at /opt/zephyr-sdk-0.16.8"

      - name: Debug Checkout
        run: |
          echo "Root: /home/runner/work/BlueBerry_Q20/BlueBerry_Q20"
          ls -la /home/runner/work/BlueBerry_Q20/BlueBerry_Q20/config || echo "config/ missing"
          cat /home/runner/work/BlueBerry_Q20/BlueBerry_Q20/config/west.yml || echo "west.yml missing"

      - name: West Init
        run: west init -l /home/runner/work/BlueBerry_Q20/BlueBerry_Q20/config

      - name: West Update
        run: west update --fetch always

      - name: Debug ZMK Version
        run: |
          cd /home/runner/work/BlueBerry_Q20/BlueBerry_Q20/zmk
          git rev-parse HEAD || echo "Git commit not found"
          git log -1 --pretty=format:"%h - %s (%ci)" || echo "Git log failed"
          ls -la /home/runner/work/BlueBerry_Q20/BlueBerry_Q20/zmk/app/include/dt-bindings/zmk || echo "input_transform.h missing"
          ls -la /home/runner/work/BlueBerry_Q20/BlueBerry_Q20/zephyr || echo "zephyr/ missing"
          ls -la /home/runner/work/BlueBerry_Q20/BlueBerry_Q20/zephyr/share/zephyr-package/cmake || echo "Zephyr CMake missing"

      - name: Build
        run: |
          cd /home/runner/work/BlueBerry_Q20/BlueBerry_Q20/zmk/app
          export Zephyr_DIR=/home/runner/work/BlueBerry_Q20/BlueBerry_Q20/zephyr/share/zephyr-package/cmake
          export ZEPHYR_TOOLCHAIN_VARIANT=zephyr
          export ZEPHYR_SDK_INSTALL_DIR=/opt/zephyr-sdk-0.16.8
          west build -p -b bbq20 -- -DZMK_CONFIG=/home/runner/work/BlueBerry_Q20/BlueBerry_Q20/config -I/home/runner/work/BlueBerry_Q20/BlueBerry_Q20/zmk/app/include
