name: Build ZMK Firmware
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install West
        run: pip install west

      - name: Debug Checkout
        run: |
          echo "Root: /home/runner/work/BlueBerry_Q20/BlueBerry_Q20"
          ls -la /home/runner/work/BlueBerry_Q20/BlueBerry_Q20/config || echo "config/ missing"
          cat /home/runner/work/BlueBerry_Q20/BlueBerry_Q20/config/west.yml || echo "west.yml missing"

      - name: West Init
        run: west init -l /home/runner/work/BlueBerry_Q20/BlueBerry_Q20/config

      - name: West Update
        run: west update --fetch always

      - name: Debug ZMK
        run: |
          ls -la /home/runner/work/BlueBerry_Q20/BlueBerry_Q20/zmk/app/include/dt-bindings/zmk || echo "input_transform.h missing"
          ls -la /home/runner/work/BlueBerry_Q20/BlueBerry_Q20/zephyr || echo "zephyr/ missing"
          ls -la /home/runner/work/BlueBerry_Q20/BlueBerry_Q20/zephyr/share/zephyr-package/cmake || echo "Zephyr CMake missing"

      - name: Build
        run: |
          cd /home/runner/work/BlueBerry_Q20/BlueBerry_Q20/zmk/app
          export Zephyr_DIR=/home/runner/work/BlueBerry_Q20/BlueBerry_Q20/zephyr/share/zephyr-package/cmake
          west build -p -b bbq20 -- -DZMK_CONFIG=/home/runner/work/BlueBerry_Q20/BlueBerry_Q20/config
