name: Build ZMK Firmware
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to ensure we can reset

      - name: Install West
        run: pip install west

      - name: Install Zephyr SDK
        run: |
          wget -q https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.8/zephyr-sdk-0.16.8_linux-x86_64.tar.xz
          tar -xJf zephyr-sdk-0.16.8_linux-x86_64.tar.xz -C /opt
          /opt/zephyr-sdk-0.16.8/setup.sh -t arm-zephyr-eabi

      - name: Debug Checkout
        run: |
          echo "Root: /home/runner/work/BlueBerry_Q20/BlueBerry_Q20"
          ls -la /home/runner/work/BlueBerry_Q20/BlueBerry_Q20/config

      - name: West Init
        run: west init -m https://github.com/zmkfirmware/zmk --mr main

      - name: West Update
        run: |
          cd /home/runner/work/BlueBerry_Q20/BlueBerry_Q20
          west update --fetch always --narrow --rebase
          # Ensure ZMK is at the latest main
          cd zmk
          git reset --hard origin/main
          # Move your config into place (assuming config/ is your custom manifest)
          mv config /home/runner/work/BlueBerry_Q20/BlueBerry_Q20/zmk/app/

      - name: Debug ZMK Version
        run: |
          cd /home/runner/work/BlueBerry_Q20/BlueBerry_Q20/zmk
          git rev-parse HEAD > zmk_version.txt
          git log -1 --pretty=format:"%h - %s (%ci)" >> zmk_version.txt
          cat zmk_version.txt
          ls -la /home/runner/work/BlueBerry_Q20/BlueBerry_Q20/zmk/app/include/dt-bindings/zmk || echo "input_transform.h missing"

      - name: Build
        run: |
          cd /home/runner/work/BlueBerry_Q20/BlueBerry_Q20/zmk/app
          export Zephyr_DIR=/home/runner/work/BlueBerry_Q20/BlueBerry_Q20/zephyr/share/zephyr-package/cmake
          export ZEPHYR_TOOLCHAIN_VARIANT=zephyr
          export ZEPHYR_SDK_INSTALL_DIR=/opt/zephyr-sdk-0.16.8
          west build -p -b bbq20 -- -DZMK_CONFIG=/home/runner/work/BlueBerry_Q20/BlueBerry_Q20/zmk/app/config -I/home/runner/work/BlueBerry_Q20/BlueBerry_Q20/zmk/app/include
