name: Build ZMK Firmware
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3  # Clones to ${{ github.workspace }}

      - name: Install West
        run: pip install west

      - name: Debug Checkout
        run: |
          echo "Workspace: ${{ github.workspace }}"
          pwd
          ls -la
          ls -la config || echo "config/ not found"
          cat config/west.yml || echo "west.yml missing"

      - name: West Init
        run: |
          west init -l config || echo "Init failed"

      - name: West Update
        run: |
          west update --fetch always || echo "Update failed"
          ls -la zmk || echo "zmk/ not found"
          ls -la zmk/app || echo "zmk/app/ not found"
          ls -la zmk/app/include/dt-bindings/zmk || echo "dt-bindings not found"

      - name: Build
        run: |
          cd zmk || echo "cd zmk failed"
          pwd
          ls -la
          ls -la app || echo "app/ not found"
          west build -p -b nice_nano_v2 -- -DSHIELD=bbq20 -DZMK_CONFIG=${{ github.workspace }}/config || echo "Build failed"
