name: Build ZMK Firmware
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - board: nice_nano_v2  # Adjust if your controller differs
            shield: bbq20
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3  # Clones to ${{ github.workspace }}

      - name: Install West
        run: pip install west

      - name: West Init
        run: west init -l config  # Uses ${{ github.workspace }}/config/west.yml

      - name: West Update
        run: |
          west update --fetch always
          ls -la zmk/app/include/dt-bindings/zmk/ || echo "ZMK fetch failed"

      - name: Build
        run: |
          cd zmk  # Move to ZMK source directory
          west build -p -b ${{ matrix.board }} -- -DSHIELD=${{ matrix.shield }} -DZMK_CONFIG=${{ github.workspace }}/config
