name: Build ZMK Firmware
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install West
        run: pip install west

      - name: Debug Checkout
        run: |
          echo "Workspace: ${{ github.workspace }}"
          ls -la config || echo "config/ missing"
          cat config/west.yml || echo "west.yml missing"

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update --fetch always

      - name: Debug ZMK
        run: |
          ls -la zmk/app/include/dt-bindings/zmk || echo "input_transform.h missing"
          ls -la zephyr || echo "zephyr/ missing"
          ls -la zephyr/share/zephyr-package/cmake || echo "Zephyr CMake missing"

      - name: Build
        run: |
          cd zmk/app
          echo "Zephyr base: ${{ github.workspace }}/zephyr"
          ls -la ${{ github.workspace }}/zephyr || echo "Zephyr not found"
          export ZEPHYR_BASE=${{ github.workspace }}/zephyr
          west build -p -b nice_nano_v2 -- -DSHIELD=bbq20 -DZMK_CONFIG=${{ github.workspace }}/config
